#include "GetParameterTypes_Response_SplDcps.h"
#include "ccpp_GetParameterTypes_Response_.h"
#include "dds_type_aliases.h"

const char *
__rcl_interfaces_srv_dds__GetParameterTypes_Response___name(void)
{
    return (const char*)"rcl_interfaces::srv::dds_::GetParameterTypes_Response_";
}

const char *
__rcl_interfaces_srv_dds__GetParameterTypes_Response___keys(void)
{
    return (const char*)"";
}

#include <v_kernel.h>
#include <v_topic.h>
#include <os_stdlib.h>
#include <string.h>
#include <os_report.h>

c_bool
__rcl_interfaces_srv_dds__GetParameterTypes_Response___copyIn(
    c_base base,
    struct ::rcl_interfaces::srv::dds_::GetParameterTypes_Response_ *from,
    struct _rcl_interfaces_srv_dds__GetParameterTypes_Response_ *to)
{
    c_bool result = OS_C_TRUE;
    (void) base;

    {
/* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 774 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_long length0;
        c_octet *dest0;
        ::rcl_interfaces::srv::dds_::GetParameterTypes_Response_::_types__seq *src = &from->types_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "c_octet"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<c_octet>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_long)(*src).length();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (c_octet *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_octet *buf0;
            buf0 = (c_octet *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->types_ = (c_sequence)dest0;
#else
        dest0 = (c_octet *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_octet *buf0;
            buf0 = (c_octet *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->types_ = (c_sequence)dest0;
#endif
    }
    return result;
}

void
__rcl_interfaces_srv_dds__GetParameterTypes_Response___copyOut(
    void *_from,
    void *_to)
{
    struct _rcl_interfaces_srv_dds__GetParameterTypes_Response_ *from = (struct _rcl_interfaces_srv_dds__GetParameterTypes_Response_ *)_from;
    struct ::rcl_interfaces::srv::dds_::GetParameterTypes_Response_ *to = (struct ::rcl_interfaces::srv::dds_::GetParameterTypes_Response_ *)_to;
    {
        long size0;
        c_octet *src0 = (c_octet *)from->types_;
        ::rcl_interfaces::srv::dds_::GetParameterTypes_Response_::_types__seq *dst = &to->types_;

        size0 = c_arraySize(c_sequence(from->types_));
        to->types_.length(size0);
        {
            c_octet *buf0;
            buf0 = (c_octet *)(*dst).get_buffer();
            memcpy (buf0,src0,size0* sizeof(*buf0));
        }
    }
}

