//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetParameters_Request_Dcps.h
//  Source: rcl_interfaces/srv/dds_opensplice/GetParameters_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _GETPARAMETERS_REQUEST_DCPS_H_
#define _GETPARAMETERS_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "GetParameters_Request_.h"
#include "dds_dcps.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {

         class GetParameters_Request_TypeSupportInterface;

         typedef GetParameters_Request_TypeSupportInterface * GetParameters_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < GetParameters_Request_TypeSupportInterface> GetParameters_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < GetParameters_Request_TypeSupportInterface> GetParameters_Request_TypeSupportInterface_out;


         class GetParameters_Request_DataWriter;

         typedef GetParameters_Request_DataWriter * GetParameters_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < GetParameters_Request_DataWriter> GetParameters_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < GetParameters_Request_DataWriter> GetParameters_Request_DataWriter_out;


         class GetParameters_Request_DataReader;

         typedef GetParameters_Request_DataReader * GetParameters_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < GetParameters_Request_DataReader> GetParameters_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < GetParameters_Request_DataReader> GetParameters_Request_DataReader_out;


         class GetParameters_Request_DataReaderView;

         typedef GetParameters_Request_DataReaderView * GetParameters_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < GetParameters_Request_DataReaderView> GetParameters_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < GetParameters_Request_DataReaderView> GetParameters_Request_DataReaderView_out;

         struct GetParameters_Request_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < GetParameters_Request_, struct GetParameters_Request_Seq_uniq_> GetParameters_Request_Seq;
         typedef DDS_DCPSSequence_var < GetParameters_Request_Seq> GetParameters_Request_Seq_var;
         typedef DDS_DCPSSequence_out < GetParameters_Request_Seq> GetParameters_Request_Seq_out;
         class GetParameters_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef GetParameters_Request_TypeSupportInterface_ptr _ptr_type;
            typedef GetParameters_Request_TypeSupportInterface_var _var_type;

            static GetParameters_Request_TypeSupportInterface_ptr _duplicate (GetParameters_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameters_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static GetParameters_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameters_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameters_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            GetParameters_Request_TypeSupportInterface () {};
            ~GetParameters_Request_TypeSupportInterface () {};
         private:
            GetParameters_Request_TypeSupportInterface (const GetParameters_Request_TypeSupportInterface &);
            GetParameters_Request_TypeSupportInterface & operator = (const GetParameters_Request_TypeSupportInterface &);
         };

         class GetParameters_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef GetParameters_Request_DataWriter_ptr _ptr_type;
            typedef GetParameters_Request_DataWriter_var _var_type;

            static GetParameters_Request_DataWriter_ptr _duplicate (GetParameters_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameters_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameters_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const GetParameters_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const GetParameters_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const GetParameters_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const GetParameters_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const GetParameters_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const GetParameters_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const GetParameters_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const GetParameters_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const GetParameters_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const GetParameters_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (GetParameters_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameters_Request_& instance_data) = 0;

         protected:
            GetParameters_Request_DataWriter () {};
            ~GetParameters_Request_DataWriter () {};
         private:
            GetParameters_Request_DataWriter (const GetParameters_Request_DataWriter &);
            GetParameters_Request_DataWriter & operator = (const GetParameters_Request_DataWriter &);
         };

         class GetParameters_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef GetParameters_Request_DataReader_ptr _ptr_type;
            typedef GetParameters_Request_DataReader_var _var_type;

            static GetParameters_Request_DataReader_ptr _duplicate (GetParameters_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameters_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameters_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetParameters_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetParameters_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetParameters_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameters_Request_& instance) = 0;

         protected:
            GetParameters_Request_DataReader () {};
            ~GetParameters_Request_DataReader () {};
         private:
            GetParameters_Request_DataReader (const GetParameters_Request_DataReader &);
            GetParameters_Request_DataReader & operator = (const GetParameters_Request_DataReader &);
         };

         class GetParameters_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef GetParameters_Request_DataReaderView_ptr _ptr_type;
            typedef GetParameters_Request_DataReaderView_var _var_type;

            static GetParameters_Request_DataReaderView_ptr _duplicate (GetParameters_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameters_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameters_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameters_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetParameters_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetParameters_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetParameters_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetParameters_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameters_Request_& instance) = 0;

         protected:
            GetParameters_Request_DataReaderView () {};
            ~GetParameters_Request_DataReaderView () {};
         private:
            GetParameters_Request_DataReaderView (const GetParameters_Request_DataReaderView &);
            GetParameters_Request_DataReaderView & operator = (const GetParameters_Request_DataReaderView &);
         };

      }
   }
}




#endif 
