//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListParameters_Request_.cpp
//  Source: rcl_interfaces/srv/dds_opensplice/ListParameters_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ListParameters_Request_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::String, struct _prefixes__seq_uniq_>;
#endif



