//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SetParametersAtomically_Request_Dcps.h
//  Source: rcl_interfaces/srv/dds_opensplice/SetParametersAtomically_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _SETPARAMETERSATOMICALLY_REQUEST_DCPS_H_
#define _SETPARAMETERSATOMICALLY_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "dds_dcps.h"
#include "SetParametersAtomically_Request_.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {

         class SetParametersAtomically_Request_TypeSupportInterface;

         typedef SetParametersAtomically_Request_TypeSupportInterface * SetParametersAtomically_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < SetParametersAtomically_Request_TypeSupportInterface> SetParametersAtomically_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < SetParametersAtomically_Request_TypeSupportInterface> SetParametersAtomically_Request_TypeSupportInterface_out;


         class SetParametersAtomically_Request_DataWriter;

         typedef SetParametersAtomically_Request_DataWriter * SetParametersAtomically_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < SetParametersAtomically_Request_DataWriter> SetParametersAtomically_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < SetParametersAtomically_Request_DataWriter> SetParametersAtomically_Request_DataWriter_out;


         class SetParametersAtomically_Request_DataReader;

         typedef SetParametersAtomically_Request_DataReader * SetParametersAtomically_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < SetParametersAtomically_Request_DataReader> SetParametersAtomically_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < SetParametersAtomically_Request_DataReader> SetParametersAtomically_Request_DataReader_out;


         class SetParametersAtomically_Request_DataReaderView;

         typedef SetParametersAtomically_Request_DataReaderView * SetParametersAtomically_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < SetParametersAtomically_Request_DataReaderView> SetParametersAtomically_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < SetParametersAtomically_Request_DataReaderView> SetParametersAtomically_Request_DataReaderView_out;

         struct SetParametersAtomically_Request_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < SetParametersAtomically_Request_, struct SetParametersAtomically_Request_Seq_uniq_> SetParametersAtomically_Request_Seq;
         typedef DDS_DCPSSequence_var < SetParametersAtomically_Request_Seq> SetParametersAtomically_Request_Seq_var;
         typedef DDS_DCPSSequence_out < SetParametersAtomically_Request_Seq> SetParametersAtomically_Request_Seq_out;
         class SetParametersAtomically_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef SetParametersAtomically_Request_TypeSupportInterface_ptr _ptr_type;
            typedef SetParametersAtomically_Request_TypeSupportInterface_var _var_type;

            static SetParametersAtomically_Request_TypeSupportInterface_ptr _duplicate (SetParametersAtomically_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static SetParametersAtomically_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            SetParametersAtomically_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            SetParametersAtomically_Request_TypeSupportInterface () {};
            ~SetParametersAtomically_Request_TypeSupportInterface () {};
         private:
            SetParametersAtomically_Request_TypeSupportInterface (const SetParametersAtomically_Request_TypeSupportInterface &);
            SetParametersAtomically_Request_TypeSupportInterface & operator = (const SetParametersAtomically_Request_TypeSupportInterface &);
         };

         class SetParametersAtomically_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef SetParametersAtomically_Request_DataWriter_ptr _ptr_type;
            typedef SetParametersAtomically_Request_DataWriter_var _var_type;

            static SetParametersAtomically_Request_DataWriter_ptr _duplicate (SetParametersAtomically_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static SetParametersAtomically_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            SetParametersAtomically_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const SetParametersAtomically_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const SetParametersAtomically_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const SetParametersAtomically_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (SetParametersAtomically_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const SetParametersAtomically_Request_& instance_data) = 0;

         protected:
            SetParametersAtomically_Request_DataWriter () {};
            ~SetParametersAtomically_Request_DataWriter () {};
         private:
            SetParametersAtomically_Request_DataWriter (const SetParametersAtomically_Request_DataWriter &);
            SetParametersAtomically_Request_DataWriter & operator = (const SetParametersAtomically_Request_DataWriter &);
         };

         class SetParametersAtomically_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef SetParametersAtomically_Request_DataReader_ptr _ptr_type;
            typedef SetParametersAtomically_Request_DataReader_var _var_type;

            static SetParametersAtomically_Request_DataReader_ptr _duplicate (SetParametersAtomically_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static SetParametersAtomically_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            SetParametersAtomically_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (SetParametersAtomically_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (SetParametersAtomically_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (SetParametersAtomically_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const SetParametersAtomically_Request_& instance) = 0;

         protected:
            SetParametersAtomically_Request_DataReader () {};
            ~SetParametersAtomically_Request_DataReader () {};
         private:
            SetParametersAtomically_Request_DataReader (const SetParametersAtomically_Request_DataReader &);
            SetParametersAtomically_Request_DataReader & operator = (const SetParametersAtomically_Request_DataReader &);
         };

         class SetParametersAtomically_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef SetParametersAtomically_Request_DataReaderView_ptr _ptr_type;
            typedef SetParametersAtomically_Request_DataReaderView_var _var_type;

            static SetParametersAtomically_Request_DataReaderView_ptr _duplicate (SetParametersAtomically_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static SetParametersAtomically_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static SetParametersAtomically_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            SetParametersAtomically_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (SetParametersAtomically_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (SetParametersAtomically_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (SetParametersAtomically_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (SetParametersAtomically_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const SetParametersAtomically_Request_& instance) = 0;

         protected:
            SetParametersAtomically_Request_DataReaderView () {};
            ~SetParametersAtomically_Request_DataReaderView () {};
         private:
            SetParametersAtomically_Request_DataReaderView (const SetParametersAtomically_Request_DataReaderView &);
            SetParametersAtomically_Request_DataReaderView & operator = (const SetParametersAtomically_Request_DataReaderView &);
         };

      }
   }
}




#endif 
