#include "SetParametersAtomically_Request_SplDcps.h"
#include "ccpp_SetParametersAtomically_Request_.h"
#include "dds_type_aliases.h"

const char *
__rcl_interfaces_srv_dds__SetParametersAtomically_Request___name(void)
{
    return (const char*)"rcl_interfaces::srv::dds_::SetParametersAtomically_Request_";
}

const char *
__rcl_interfaces_srv_dds__SetParametersAtomically_Request___keys(void)
{
    return (const char*)"";
}

#include <v_kernel.h>
#include <v_topic.h>
#include <os_stdlib.h>
#include <string.h>
#include <os_report.h>

c_bool
__rcl_interfaces_srv_dds__SetParametersAtomically_Request___copyIn(
    c_base base,
    struct ::rcl_interfaces::srv::dds_::SetParametersAtomically_Request_ *from,
    struct _rcl_interfaces_srv_dds__SetParametersAtomically_Request_ *to)
{
    c_bool result = OS_C_TRUE;
    (void) base;

    {
/* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 774 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_long length0;
        struct _rcl_interfaces_msg_dds__Parameter_ *dest0;
        ::rcl_interfaces::srv::dds_::SetParametersAtomically_Request_::_parameters__seq *src = &from->parameters_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "rcl_interfaces::msg::dds_::Parameter_"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<rcl_interfaces::msg::dds_::Parameter_>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_long)(*src).length();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (struct _rcl_interfaces_msg_dds__Parameter_ *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1928 */
            unsigned int i0;
            for (i0 = 0; (i0 < (unsigned int)length0) && result; i0++) {
                extern c_bool __rcl_interfaces_msg_dds__Parameter___copyIn(c_base base,
                    rcl_interfaces::msg::dds_::Parameter_ *From,
                    struct _rcl_interfaces_msg_dds__Parameter_ *To);

                result = __rcl_interfaces_msg_dds__Parameter___copyIn(base, &(*src)[i0], (struct _rcl_interfaces_msg_dds__Parameter_ *)&dest0[i0]);
            }
        }
        to->parameters_ = (c_sequence)dest0;
#else
        dest0 = (struct _rcl_interfaces_msg_dds__Parameter_ *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1928 */
            unsigned int i0;
            for (i0 = 0; (i0 < (unsigned int)length0) && result; i0++) {
                extern c_bool __rcl_interfaces_msg_dds__Parameter___copyIn(c_base base,
                    rcl_interfaces::msg::dds_::Parameter_ *From,
                    struct _rcl_interfaces_msg_dds__Parameter_ *To);

                result = __rcl_interfaces_msg_dds__Parameter___copyIn(base, &(*src)[i0], (struct _rcl_interfaces_msg_dds__Parameter_ *)&dest0[i0]);
            }
        }
        to->parameters_ = (c_sequence)dest0;
#endif
    }
    return result;
}

void
__rcl_interfaces_srv_dds__SetParametersAtomically_Request___copyOut(
    void *_from,
    void *_to)
{
    struct _rcl_interfaces_srv_dds__SetParametersAtomically_Request_ *from = (struct _rcl_interfaces_srv_dds__SetParametersAtomically_Request_ *)_from;
    struct ::rcl_interfaces::srv::dds_::SetParametersAtomically_Request_ *to = (struct ::rcl_interfaces::srv::dds_::SetParametersAtomically_Request_ *)_to;
    {
        long size0;
        struct _rcl_interfaces_msg_dds__Parameter_ *src0 = (struct _rcl_interfaces_msg_dds__Parameter_ *)from->parameters_;
        ::rcl_interfaces::srv::dds_::SetParametersAtomically_Request_::_parameters__seq *dst = &to->parameters_;

        size0 = c_arraySize(c_sequence(from->parameters_));
        to->parameters_.length(size0);
        {
            long i0;
            for (i0 = 0; i0 < size0; i0++) {
                extern void __rcl_interfaces_msg_dds__Parameter___copyOut(void *from, void *to);
                __rcl_interfaces_msg_dds__Parameter___copyOut((void *)&src0[i0], (void *)&(*dst)[i0]);
            }
        }
    }
}

