//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Bool_.h
//  Source: std_msgs/msg/dds_opensplice/Bool_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _BOOL__H_
#define _BOOL__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Bool_;

         struct Bool_
         {
               DDS::Boolean data_;
         };

         typedef DDS_DCPSStruct_var < Bool_> Bool__var;
         typedef Bool_&Bool__out;
      }
   }
}




#endif 
