//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Bool_.cpp
//  Source: std_msgs/msg/dds_opensplice/Bool_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Bool_.h"




