//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ByteMultiArray_.cpp
//  Source: std_msgs/msg/dds_opensplice/ByteMultiArray_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ByteMultiArray_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct _data__seq_uniq_>;
#endif



