//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Char_.h
//  Source: std_msgs/msg/dds_opensplice/Char_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _CHAR__H_
#define _CHAR__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Char_;

         struct Char_
         {
               DDS::Char data_;
         };

         typedef DDS_DCPSStruct_var < Char_> Char__var;
         typedef Char_&Char__out;
      }
   }
}




#endif 
