//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Char_.cpp
//  Source: std_msgs/msg/dds_opensplice/Char_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Char_.h"




