//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ColorRGBA_.cpp
//  Source: std_msgs/msg/dds_opensplice/ColorRGBA_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ColorRGBA_.h"




