//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Empty_.cpp
//  Source: std_msgs/msg/dds_opensplice/Empty_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Empty_.h"




