//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Float32MultiArray_.cpp
//  Source: std_msgs/msg/dds_opensplice/Float32MultiArray_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Float32MultiArray_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Float, struct _data__seq_uniq_>;
#endif



