//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Float64_.h
//  Source: std_msgs/msg/dds_opensplice/Float64_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _FLOAT64__H_
#define _FLOAT64__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Float64_;

         struct Float64_
         {
               DDS::Double data_;
         };

         typedef DDS_DCPSStruct_var < Float64_> Float64__var;
         typedef Float64_&Float64__out;
      }
   }
}




#endif 
