//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Float32_.cpp
//  Source: std_msgs/msg/dds_opensplice/Float32_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Float32_.h"




