//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int16_.cpp
//  Source: std_msgs/msg/dds_opensplice/Int16_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Int16_.h"




