//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int32_.h
//  Source: std_msgs/msg/dds_opensplice/Int32_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _INT32__H_
#define _INT32__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Int32_;

         struct Int32_
         {
               DDS::Long data_;
         };

         typedef DDS_DCPSStruct_var < Int32_> Int32__var;
         typedef Int32_&Int32__out;
      }
   }
}




#endif 
