//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int64_.cpp
//  Source: std_msgs/msg/dds_opensplice/Int64_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Int64_.h"




