//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int8_.cpp
//  Source: std_msgs/msg/dds_opensplice/Int8_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Int8_.h"




