//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt8_.cpp
//  Source: std_msgs/msg/dds_opensplice/UInt8_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "UInt8_.h"




