//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt8_.h
//  Source: std_msgs/msg/dds_opensplice/UInt8_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _UINT8__H_
#define _UINT8__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct UInt8_;

         struct UInt8_
         {
               DDS::Octet data_;
         };

         typedef DDS_DCPSStruct_var < UInt8_> UInt8__var;
         typedef UInt8_&UInt8__out;
      }
   }
}




#endif 
