//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt16_.h
//  Source: std_msgs/msg/dds_opensplice/UInt16_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _UINT16__H_
#define _UINT16__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct UInt16_;

         struct UInt16_
         {
               DDS::UShort data_;
         };

         typedef DDS_DCPSStruct_var < UInt16_> UInt16__var;
         typedef UInt16_&UInt16__out;
      }
   }
}




#endif 
