//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt16MultiArray_.h
//  Source: std_msgs/msg/dds_opensplice/UInt16MultiArray_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _UINT16MULTIARRAY__H_
#define _UINT16MULTIARRAY__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "MultiArrayLayout_.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct UInt16MultiArray_;

         struct UInt16MultiArray_
         {
               struct _data__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::UShort, struct _data__seq_uniq_> _data__seq;
               typedef DDS_DCPSSequence_var < _data__seq> _data__seq_var;
               typedef DDS_DCPSSequence_out < _data__seq> _data__seq_out;
               MultiArrayLayout_ layout_;
               _data__seq data_;
         };

         typedef DDS_DCPSStruct_var < UInt16MultiArray_> UInt16MultiArray__var;
         typedef DDS_DCPSStruct_out < UInt16MultiArray_> UInt16MultiArray__out;
      }
   }
}




#endif 
