//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt32_.h
//  Source: std_msgs/msg/dds_opensplice/UInt32_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _UINT32__H_
#define _UINT32__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct UInt32_;

         struct UInt32_
         {
               DDS::ULong data_;
         };

         typedef DDS_DCPSStruct_var < UInt32_> UInt32__var;
         typedef UInt32_&UInt32__out;
      }
   }
}




#endif 
