// generated from rosidl_typesupport_introspection_c/resource/srv__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef RCL_INTERFACES__SRV__SET_PARAMETERS__INTROSPECTION_TYPE_SUPPORT_H_
#define RCL_INTERFACES__SRV__SET_PARAMETERS__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/service_type_support.h>

#include "rcl_interfaces/msg/rosidl_generator_c__visibility_control.h"

static rosidl_service_type_support_t rcl_interfaces__srv__rosidl_typesupport_introspection_c__SetParameters_service_type_support_handle;

#endif  // RCL_INTERFACES__SRV__SET_PARAMETERS__INTROSPECTION_TYPE_SUPPORT_H_
