INCLUDES += -I$(ROS2BASE)/rcl/rcl/include
INCLUDES += -I$(ROS2BASE)/rcl/rcl/src/rcl/stdatomic_helper/gcc
INCLUDES += -I$(ROS2BASE)/rclcpp/rclcpp/include
INCLUDES += -I$(ROS2BASE)/rmw/rmw/include

INCLUDES += -I$(ROS2BASE)/src/rclc/include

INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_generator_c/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_interface/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_cpp/include

INCLUDES += -I$(ROS2BASE)/generated/rcl_interfaces/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/generated/builtin_interfaces/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/generated/std_msgs/rosidl_generator_cpp/include

INCLUDES += -I$(ROS2BASE)/generated/builtin_interfaces/rosidl_generator_c/include
INCLUDES += -I$(ROS2BASE)/generated/std_msgs/rosidl_generator_c/include

CXXEXFLAGS += -std=c++14
CFLAGS += -std=c11

CFLAGS += -Drosidl_typesupport_cpp=rosidl_typesupport_introspection_cpp

ifneq (,$(filter rosidl_typesupport_introspection_c,$(USEMODULE)))
    INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_c/include
    INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_c/include/rosidl_typesupport_introspection_c/impl
endif

ifneq (,$(filter rosidl_typesupport_test,$(USEMODULE)))
    INCLUDES += -I$(ROS2BASE)/rosidl_typesupport_test/include
    INCLUDES += -I$(ROS2BASE)/rosidl_typesupport_test/include/rosidl_typesupport_test/impl
    INCLUDES += -I$(ROS2BASE)/generated/std_msgs/rosidl_typesupport_test/include
    
    USEMODULE += cbor
endif

ifneq (,$(filter rcl,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter rmw_ndn,$(USEMODULE)))
    EXTERNAL_MODULE_DIRS += $(CURDIR)/../../ndn-riot
    USEMODULE += gnrc_netdev_default
    USEMODULE += auto_init_gnrc_netif
    USEMODULE += ndn-riot
    INCLUDES += -I$(ROS2BASE)/.
endif

ifneq (,$(filter rmw_mqtt,$(USEMODULE)))
    USEMODULE += gnrc_netdev_default
    USEMODULE += auto_init_gnrc_netif
    USEMODULE += gnrc_sock_udp
    USEMODULE += gnrc_ipv6_default
    USEMODULE += emcute
    
    BROKERADDR ?= fec0:affe::1
    
    ifdef MYADDR
        CFLAGS += -DMYADDR=\"$(MYADDR)\"
    endif
    
    CFLAGS += -DBROKERADDR=\"$(BROKERADDR)\"
endif

USEMODULE += cpp11-compat
