INCLUDES += -I$(ROS2BASE)/rcl/rcl/include
INCLUDES += -I$(ROS2BASE)/rclcpp/rclcpp/include
INCLUDES += -I$(ROS2BASE)/rmw/rmw/include

INCLUDES += -I$(ROS2BASE)/src/rclc/include

INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_generator_c/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_interface/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_cpp/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_c/include
INCLUDES += -I$(ROS2BASE)/rosidl/rosidl_typesupport_introspection_c/include/rosidl_typesupport_introspection_c/impl

INCLUDES += -I$(ROS2BASE)/generated/rcl_interfaces/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/generated/builtin_interfaces/rosidl_generator_cpp/include
INCLUDES += -I$(ROS2BASE)/generated/std_msgs/rosidl_generator_cpp/include

INCLUDES += -I$(ROS2BASE)/generated/builtin_interfaces/rosidl_generator_c/include
INCLUDES += -I$(ROS2BASE)/generated/std_msgs/rosidl_generator_c/include

CXXEXFLAGS += -std=c++14
CFLAGS += -std=c11

CFLAGS += -Drosidl_typesupport_cpp=rosidl_typesupport_introspection_cpp

ifneq (,$(filter rcl,$(USEMODULE)))
    USEMODULE += xtimer
endif
