//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Parameter_.h
//  Source: rcl_interfaces/msg/dds_opensplice/Parameter_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _PARAMETER__H_
#define _PARAMETER__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "ParameterValue_.h"


namespace rcl_interfaces
{
   namespace msg
   {
      namespace dds_
      {
         struct Parameter_;

         struct Parameter_
         {
               DDS::String_mgr name_;
               ParameterValue_ value_;
         };

         typedef DDS_DCPSStruct_var < Parameter_> Parameter__var;
         typedef DDS_DCPSStruct_out < Parameter_> Parameter__out;
      }
   }
}




#endif 
