//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ParameterEvent_Dcps.cpp
//  Source: rcl_interfaces/msg/dds_opensplice/ParameterEvent_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ParameterEvent_Dcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < rcl_interfaces::msg::dds_::ParameterEvent_, struct ParameterEvent_Seq_uniq_>;
#endif

const char * rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_local_id = "IDL:rcl_interfaces/msg/dds_/ParameterEvent_TypeSupportInterface:1.0";

rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_duplicate (rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_local_id))
   {
      result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr result;
   result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_TypeSupportInterface_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_local_id = "IDL:rcl_interfaces/msg/dds_/ParameterEvent_DataWriter:1.0";

rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_duplicate (rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr result = NULL;
   if (p && p->_is_a (rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_local_id))
   {
      result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr result;
   result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataWriter_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_local_id = "IDL:rcl_interfaces/msg/dds_/ParameterEvent_DataReader:1.0";

rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_duplicate (rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr result = NULL;
   if (p && p->_is_a (rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_local_id))
   {
      result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr result;
   result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataReader_ptr> (p);
   if (result) result->m_count++;
   return result;
}

const char * rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_local_id = "IDL:rcl_interfaces/msg/dds_/ParameterEvent_DataReaderView:1.0";

rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_duplicate (rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr result = NULL;
   if (p && p->_is_a (rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_local_id))
   {
      result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr> (p);
      if (result) result->m_count++;
   }
   return result;
}

rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr result;
   result = dynamic_cast < rcl_interfaces::msg::dds_::ParameterEvent_DataReaderView_ptr> (p);
   if (result) result->m_count++;
   return result;
}



