//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ParameterEventDescriptors_.cpp
//  Source: rcl_interfaces/msg/dds_opensplice/ParameterEventDescriptors_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ParameterEventDescriptors_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < rcl_interfaces::msg::dds_::ParameterDescriptor_, struct _deleted_parameters__seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < rcl_interfaces::msg::dds_::ParameterDescriptor_, struct _changed_parameters__seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < rcl_interfaces::msg::dds_::ParameterDescriptor_, struct _new_parameters__seq_uniq_>;
#endif



