//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Empty_.h
//  Source: std_msgs/msg/dds_opensplice/Empty_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _EMPTY__H_
#define _EMPTY__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Empty_;

         struct Empty_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < Empty_> Empty__var;
         typedef Empty_&Empty__out;
      }
   }
}




#endif 
