//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Header_.cpp
//  Source: std_msgs/msg/dds_opensplice/Header_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Header_.h"




