//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int16_.h
//  Source: std_msgs/msg/dds_opensplice/Int16_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _INT16__H_
#define _INT16__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Int16_;

         struct Int16_
         {
               DDS::Short data_;
         };

         typedef DDS_DCPSStruct_var < Int16_> Int16__var;
         typedef Int16_&Int16__out;
      }
   }
}




#endif 
