//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int32_.cpp
//  Source: std_msgs/msg/dds_opensplice/Int32_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "Int32_.h"




