//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MultiArrayDimension_.cpp
//  Source: std_msgs/msg/dds_opensplice/MultiArrayDimension_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "MultiArrayDimension_.h"




