//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MultiArrayLayout_.cpp
//  Source: std_msgs/msg/dds_opensplice/MultiArrayLayout_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "MultiArrayLayout_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < std_msgs::msg::dds_::MultiArrayDimension_, struct _dim__seq_uniq_>;
#endif



