//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: String_.cpp
//  Source: std_msgs/msg/dds_opensplice/String_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "String_.h"




