//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: String_.h
//  Source: std_msgs/msg/dds_opensplice/String_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _STRING__H_
#define _STRING__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct String_;

         struct String_
         {
               DDS::String_mgr data_;
         };

         typedef DDS_DCPSStruct_var < String_> String__var;
         typedef DDS_DCPSStruct_out < String_> String__out;
      }
   }
}




#endif 
