//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt64_.h
//  Source: std_msgs/msg/dds_opensplice/UInt64_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _UINT64__H_
#define _UINT64__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct UInt64_;

         struct UInt64_
         {
               DDS::ULongLong data_;
         };

         typedef DDS_DCPSStruct_var < UInt64_> UInt64__var;
         typedef UInt64_&UInt64__out;
      }
   }
}




#endif 
