//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt16_.cpp
//  Source: std_msgs/msg/dds_opensplice/UInt16_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "UInt16_.h"




