//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: UInt32MultiArray_.cpp
//  Source: std_msgs/msg/dds_opensplice/UInt32MultiArray_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "UInt32MultiArray_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::ULong, struct _data__seq_uniq_>;
#endif



