//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: IntraProcessMessage_.h
//  Source: rcl_interfaces/msg/dds_opensplice/IntraProcessMessage_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _INTRAPROCESSMESSAGE__H_
#define _INTRAPROCESSMESSAGE__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace rcl_interfaces
{
   namespace msg
   {
      namespace dds_
      {
         struct IntraProcessMessage_;

         struct IntraProcessMessage_
         {
               DDS::ULongLong publisher_id_;
               DDS::ULongLong message_sequence_;
         };

         typedef DDS_DCPSStruct_var < IntraProcessMessage_> IntraProcessMessage__var;
         typedef IntraProcessMessage_&IntraProcessMessage__out;
      }
   }
}




#endif 
