//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListParametersResult_.cpp
//  Source: rcl_interfaces/msg/dds_opensplice/ListParametersResult_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ListParametersResult_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::String, struct _prefixes__seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::String, struct _names__seq_uniq_>;
#endif



