#include "ParameterValue_SplDcps.h"
#include "ccpp_ParameterValue_.h"
#include "dds_type_aliases.h"

const char *
__rcl_interfaces_msg_dds__ParameterValue___name(void)
{
    return (const char*)"rcl_interfaces::msg::dds_::ParameterValue_";
}

const char *
__rcl_interfaces_msg_dds__ParameterValue___keys(void)
{
    return (const char*)"";
}

#include <v_kernel.h>
#include <v_topic.h>
#include <os_stdlib.h>
#include <string.h>
#include <os_report.h>

c_bool
__rcl_interfaces_msg_dds__ParameterValue___copyIn(
    c_base base,
    struct ::rcl_interfaces::msg::dds_::ParameterValue_ *from,
    struct _rcl_interfaces_msg_dds__ParameterValue_ *to)
{
    c_bool result = OS_C_TRUE;
    (void) base;

    to->type_ = (c_octet)from->type_;
    to->bool_value_ = (c_bool)from->bool_value_;
    to->integer_value_ = (c_longlong)from->integer_value_;
    to->double_value_ = (c_double)from->double_value_;
#ifdef OSPL_BOUNDS_CHECK
    if(from->string_value_){
        to->string_value_ = c_stringNew(base, from->string_value_);
    } else {
        OS_REPORT (OS_ERROR, "copyIn", 0,"Member 'rcl_interfaces::msg::dds_::ParameterValue_.string_value_' of type 'c_string' is NULL.");
        result = OS_C_FALSE;
    }
#else
    to->string_value_ = c_stringNew(base, from->string_value_);
#endif
    {
/* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 774 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_long length0;
        c_octet *dest0;
        ::rcl_interfaces::msg::dds_::ParameterValue_::_bytes_value__seq *src = &from->bytes_value_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "c_octet"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<c_octet>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_long)(*src).length();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (c_octet *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_octet *buf0;
            buf0 = (c_octet *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->bytes_value_ = (c_sequence)dest0;
#else
        dest0 = (c_octet *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /private/tmp/opensplice-20170321-33051-1xv1o2s/opensplice/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_octet *buf0;
            buf0 = (c_octet *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->bytes_value_ = (c_sequence)dest0;
#endif
    }
    return result;
}

void
__rcl_interfaces_msg_dds__ParameterValue___copyOut(
    void *_from,
    void *_to)
{
    struct _rcl_interfaces_msg_dds__ParameterValue_ *from = (struct _rcl_interfaces_msg_dds__ParameterValue_ *)_from;
    struct ::rcl_interfaces::msg::dds_::ParameterValue_ *to = (struct ::rcl_interfaces::msg::dds_::ParameterValue_ *)_to;
    to->type_ = (::DDS::Octet)from->type_;
    to->bool_value_ = (::DDS::Boolean)(from->bool_value_ != 0);
    to->integer_value_ = (::DDS::LongLong)from->integer_value_;
    to->double_value_ = (::DDS::Double)from->double_value_;
    to->string_value_ = DDS::string_dup(from->string_value_ ? from->string_value_ : "");
    {
        long size0;
        c_octet *src0 = (c_octet *)from->bytes_value_;
        ::rcl_interfaces::msg::dds_::ParameterValue_::_bytes_value__seq *dst = &to->bytes_value_;

        size0 = c_arraySize(c_sequence(from->bytes_value_));
        to->bytes_value_.length(size0);
        {
            c_octet *buf0;
            buf0 = (c_octet *)(*dst).get_buffer();
            memcpy (buf0,src0,size0* sizeof(*buf0));
        }
    }
}

