//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ParameterType_.h
//  Source: rcl_interfaces/msg/dds_opensplice/ParameterType_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _PARAMETERTYPE__H_
#define _PARAMETERTYPE__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace rcl_interfaces
{
   namespace msg
   {
      namespace dds_
      {
         struct ParameterType_;
         const DDS::Octet ParameterType__PARAMETER_NOT_SET = (DDS::Octet) 0;
         const DDS::Octet ParameterType__PARAMETER_BOOL = (DDS::Octet) 1;
         const DDS::Octet ParameterType__PARAMETER_INTEGER = (DDS::Octet) 2;
         const DDS::Octet ParameterType__PARAMETER_DOUBLE = (DDS::Octet) 3;
         const DDS::Octet ParameterType__PARAMETER_STRING = (DDS::Octet) 4;
         const DDS::Octet ParameterType__PARAMETER_BYTES = (DDS::Octet) 5;

         struct ParameterType_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < ParameterType_> ParameterType__var;
         typedef ParameterType_&ParameterType__out;
      }
   }
}




#endif 
