//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ParameterValue_.cpp
//  Source: rcl_interfaces/msg/dds_opensplice/ParameterValue_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ParameterValue_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct _bytes_value__seq_uniq_>;
#endif



