// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef RCL_INTERFACES__MSG__PARAMETER_EVENT_DESCRIPTORS__INTROSPECTION_TYPE_SUPPORT_H_
#define RCL_INTERFACES__MSG__PARAMETER_EVENT_DESCRIPTORS__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // RCL_INTERFACES__MSG__PARAMETER_EVENT_DESCRIPTORS__INTROSPECTION_TYPE_SUPPORT_H_
