//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DescribeParameters_Response_.h
//  Source: rcl_interfaces/srv/dds_opensplice/DescribeParameters_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _DESCRIBEPARAMETERS_RESPONSE__H_
#define _DESCRIBEPARAMETERS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "ParameterDescriptor_.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct DescribeParameters_Response_;

         struct DescribeParameters_Response_
         {
               struct _descriptors__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < ::rcl_interfaces::msg::dds_::ParameterDescriptor_, struct _descriptors__seq_uniq_> _descriptors__seq;
               typedef DDS_DCPSSequence_var < _descriptors__seq> _descriptors__seq_var;
               typedef DDS_DCPSSequence_out < _descriptors__seq> _descriptors__seq_out;
               _descriptors__seq descriptors_;
         };

         typedef DDS_DCPSStruct_var < DescribeParameters_Response_> DescribeParameters_Response__var;
         typedef DDS_DCPSStruct_out < DescribeParameters_Response_> DescribeParameters_Response__out;
      }
   }
}




#endif 
