//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetParameterTypes_Response_.cpp
//  Source: rcl_interfaces/srv/dds_opensplice/GetParameterTypes_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "GetParameterTypes_Response_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct _types__seq_uniq_>;
#endif



