//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetParameterTypes_Request_Dcps.h
//  Source: rcl_interfaces/srv/dds_opensplice/GetParameterTypes_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _GETPARAMETERTYPES_REQUEST_DCPS_H_
#define _GETPARAMETERTYPES_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "GetParameterTypes_Request_.h"
#include "dds_dcps.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {

         class GetParameterTypes_Request_TypeSupportInterface;

         typedef GetParameterTypes_Request_TypeSupportInterface * GetParameterTypes_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < GetParameterTypes_Request_TypeSupportInterface> GetParameterTypes_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < GetParameterTypes_Request_TypeSupportInterface> GetParameterTypes_Request_TypeSupportInterface_out;


         class GetParameterTypes_Request_DataWriter;

         typedef GetParameterTypes_Request_DataWriter * GetParameterTypes_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < GetParameterTypes_Request_DataWriter> GetParameterTypes_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < GetParameterTypes_Request_DataWriter> GetParameterTypes_Request_DataWriter_out;


         class GetParameterTypes_Request_DataReader;

         typedef GetParameterTypes_Request_DataReader * GetParameterTypes_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < GetParameterTypes_Request_DataReader> GetParameterTypes_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < GetParameterTypes_Request_DataReader> GetParameterTypes_Request_DataReader_out;


         class GetParameterTypes_Request_DataReaderView;

         typedef GetParameterTypes_Request_DataReaderView * GetParameterTypes_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < GetParameterTypes_Request_DataReaderView> GetParameterTypes_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < GetParameterTypes_Request_DataReaderView> GetParameterTypes_Request_DataReaderView_out;

         struct GetParameterTypes_Request_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < GetParameterTypes_Request_, struct GetParameterTypes_Request_Seq_uniq_> GetParameterTypes_Request_Seq;
         typedef DDS_DCPSSequence_var < GetParameterTypes_Request_Seq> GetParameterTypes_Request_Seq_var;
         typedef DDS_DCPSSequence_out < GetParameterTypes_Request_Seq> GetParameterTypes_Request_Seq_out;
         class GetParameterTypes_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef GetParameterTypes_Request_TypeSupportInterface_ptr _ptr_type;
            typedef GetParameterTypes_Request_TypeSupportInterface_var _var_type;

            static GetParameterTypes_Request_TypeSupportInterface_ptr _duplicate (GetParameterTypes_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameterTypes_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameterTypes_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            GetParameterTypes_Request_TypeSupportInterface () {};
            ~GetParameterTypes_Request_TypeSupportInterface () {};
         private:
            GetParameterTypes_Request_TypeSupportInterface (const GetParameterTypes_Request_TypeSupportInterface &);
            GetParameterTypes_Request_TypeSupportInterface & operator = (const GetParameterTypes_Request_TypeSupportInterface &);
         };

         class GetParameterTypes_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef GetParameterTypes_Request_DataWriter_ptr _ptr_type;
            typedef GetParameterTypes_Request_DataWriter_var _var_type;

            static GetParameterTypes_Request_DataWriter_ptr _duplicate (GetParameterTypes_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameterTypes_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameterTypes_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const GetParameterTypes_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const GetParameterTypes_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const GetParameterTypes_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (GetParameterTypes_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameterTypes_Request_& instance_data) = 0;

         protected:
            GetParameterTypes_Request_DataWriter () {};
            ~GetParameterTypes_Request_DataWriter () {};
         private:
            GetParameterTypes_Request_DataWriter (const GetParameterTypes_Request_DataWriter &);
            GetParameterTypes_Request_DataWriter & operator = (const GetParameterTypes_Request_DataWriter &);
         };

         class GetParameterTypes_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef GetParameterTypes_Request_DataReader_ptr _ptr_type;
            typedef GetParameterTypes_Request_DataReader_var _var_type;

            static GetParameterTypes_Request_DataReader_ptr _duplicate (GetParameterTypes_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameterTypes_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameterTypes_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetParameterTypes_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetParameterTypes_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetParameterTypes_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameterTypes_Request_& instance) = 0;

         protected:
            GetParameterTypes_Request_DataReader () {};
            ~GetParameterTypes_Request_DataReader () {};
         private:
            GetParameterTypes_Request_DataReader (const GetParameterTypes_Request_DataReader &);
            GetParameterTypes_Request_DataReader & operator = (const GetParameterTypes_Request_DataReader &);
         };

         class GetParameterTypes_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef GetParameterTypes_Request_DataReaderView_ptr _ptr_type;
            typedef GetParameterTypes_Request_DataReaderView_var _var_type;

            static GetParameterTypes_Request_DataReaderView_ptr _duplicate (GetParameterTypes_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetParameterTypes_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetParameterTypes_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            GetParameterTypes_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetParameterTypes_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetParameterTypes_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetParameterTypes_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetParameterTypes_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetParameterTypes_Request_& instance) = 0;

         protected:
            GetParameterTypes_Request_DataReaderView () {};
            ~GetParameterTypes_Request_DataReaderView () {};
         private:
            GetParameterTypes_Request_DataReaderView (const GetParameterTypes_Request_DataReaderView &);
            GetParameterTypes_Request_DataReaderView & operator = (const GetParameterTypes_Request_DataReaderView &);
         };

      }
   }
}




#endif 
