//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListParameters_Request_.h
//  Source: rcl_interfaces/srv/dds_opensplice/ListParameters_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _LISTPARAMETERS_REQUEST__H_
#define _LISTPARAMETERS_REQUEST__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct ListParameters_Request_;
         const DDS::ULongLong ListParameters_Request__DEPTH_RECURSIVE = (DDS::ULongLong) 0;

         struct ListParameters_Request_
         {
               struct _prefixes__seq_uniq_ {};
               typedef DDS_DCPSUStrSeqT <struct _prefixes__seq_uniq_> _prefixes__seq;
               typedef DDS_DCPSUStrSeq_var < _prefixes__seq> _prefixes__seq_var;
               typedef DDS_DCPSUStrSeq_out < _prefixes__seq> _prefixes__seq_out;
               _prefixes__seq prefixes_;
               DDS::ULongLong depth_;
         };

         typedef DDS_DCPSStruct_var < ListParameters_Request_> ListParameters_Request__var;
         typedef DDS_DCPSStruct_out < ListParameters_Request_> ListParameters_Request__out;
      }
   }
}




#endif 
