//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_DescribeParameters_Response_.h
//  Source: rcl_interfaces/srv/dds_opensplice/Sample_DescribeParameters_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _SAMPLE_DESCRIBEPARAMETERS_RESPONSE__H_
#define _SAMPLE_DESCRIBEPARAMETERS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "DescribeParameters_Response_.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_DescribeParameters_Response_;

         struct Sample_DescribeParameters_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               DescribeParameters_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_DescribeParameters_Response_> Sample_DescribeParameters_Response__var;
         typedef DDS_DCPSStruct_out < Sample_DescribeParameters_Response_> Sample_DescribeParameters_Response__out;
      }
   }
}




#endif 
